experiment:
  name: isles22_labels05_BS1_ex01
  output_dir: exps/isles22_labels05_BS1_ex01
  seed: 42

data:
  # dwi_dir: data/brats19/2d_data/images
  # mask_dir: data/brats19/2d_data/labels
  # bbox_train_json: data/brats19/bboxes/bbox_train.json
  # bbox_val_json: data/brats19/bboxes/bbox_test.json
  dwi_dir: data/isles22/2d_data/images
  mask_dir: data/isles22/2d_data/labels
  bbox_train_json: data/isles22/bboxes/bbox_train.json
  bbox_val_json: data/isles22/bboxes/bbox_test.json
  split_train: train
  split_val: test

training:
  batch_size: 2
  noise_std: 0.1
  threshold: 0.5

model:
  with_bbox: true   # true => (DWI + BBox + Noise) mode, false => (DWI + Noise) mode
  image_size: [128, 128]
  generator: UNet
  discriminator: FC5_Discriminator

system:
  device: cuda:0
  num_workers: 4
  pin_memory: true
  amp: false
